[package]
name = "HttpProxy"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}
serde = { version = "1.0.210", features = ["derive"] }
mongodb = { version = "3.1.0", features = ["sync"] }