[package]
name = "HttpProxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.40.0", features = ["full"]}
log = "0.4.22"
chrono = "0.4.38"
env_logger = "0.11.5"
serde = { version = "1.0.210", features = ["derive"] }

[dependencies.mongodb]
version = "3.0.1"