[package]
name = "SshScript"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.188"
serde_json = "1.0.127"
chrono = "0.4.38"
rand = "0.8.5"
mongodb = { version = "3.1.0", features = ["sync"] }