[package]
name = "BadVpnManager"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde_json = "1.0.128"